# Generated by Django 5.0.4 on 2024-04-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfolio',
            new_name='ContactForm',
        ),
    ]
