# Generated by Django 5.0.4 on 2024-05-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_contactenquiry_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactEnquiry',
        ),
    ]
